name: Ollama GitHub Workflow Example
on: 
  workflow_dispatch:
    inputs: 
      prompt:
        description: 'Prompt for the Ollama model'
        default: 'What is the capital of France?'
        required: true

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        volumes:
          - ollama_data:/root/.ollama

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          OLLAMA_HOST: "http://localhost:11434"
        run: |
          echo "Running tests..."
          python examples/text_generate_response.py "${{ inputs.prompt }}" >> $GITHUB_STEP_SUMMARY
